### PR TITLE
add Alyssa

### PR DESCRIPTION
**Pull request by SoyAndrea**
Hi @rladies/leadership, I have a doubt if this role is the same as [onboarding or chapter mentoring](https://rladies.org/about-us/global-team/) or if it is different from these (chapter-onboarding)?  Just to check

### CODE REVIEW

**Comment by cosimameyer** [comment]
That was exactly my question as well ☺️ here’s the screenshot with the two entries:
image
 Except that, everything looks good to me ☺️

**Comment by drmowinckels** [comment]
right, good find! Alyssa and Mouna are both chapter onboarding, so I suggest we also change Mouna's role to chapter onboarding, so they are together. Thanks!

**Comment by cosimameyer** [comment]
Changed :)

image

**Review by cosimameyer — APPROVED** [review]

**Review by SoyAndrea — COMMENTED** [review]
thank you :)

**Pull request merged**
