### PR TITLE
Add missing quote

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
@SoyAndrea The missing quote made the build fail. GitHub highlights the line in read after the missing quote, so in the future we might avoid part of the misformating by looking at the file in GitHub, see screenshot below:

image


Now, dealing with JSON/YAML means we'll often fight missing commas or quotes, that's our fate :joy:

**Comment by maelle** [comment]
Also, we should no longer merge PR if the checks are red as the checks are stable now... Should we look into adding a branch protection rule?

**Comment by drmowinckels** [comment]
@SoyAndrea we could, but I dont want to change the email right now, as leadership are looking into why the chapter prefer using the gmail over rladies mail. If this is the best point of contact right now, we should keep the email as is and rather change it later if we can.

So I think it is ok to merge when you can @SoyAndrea  :)

Thank you @maelle for the helP!

**Comment by drmowinckels** [comment]
@maelle do you have the opportunity to look into the branch protection rules and make a suggestion?

**Comment by maelle** [comment]
I opened https://github.com/rladies/rladies.github.io/issues/357 as yes I'd like to help with this but not this week so let's not make the idea a blocker :smile_cat:

**Review by SoyAndrea — APPROVED** [review]

**Pull request merged**
