### PR TITLE
FIx blog linking and taxonomies

### PR DESCRIPTION
**Pull request by drmowinckels**
changes should be visible in

- /tags
- /categories
- and links in the awesome blog list

### CODE REVIEW

**Comment by drmowinckels** [comment]
should be rebased on merge, as long as we dont tamper much more with it .

**Comment by cosimameyer** [comment]
Just a quick question for clarification: I see that we have now working links for the awesome R-Ladies’ list (that’s fantastic! 🥳) but I don’t see a difference with the categories/tags. Can you show me an example of what to expect?

I was also a bit confused by the name of the `word-cloud` because I expected it to format an actual wordcloud (but couldn’t find one). Or am I missing something?

**Comment by drmowinckels** [comment]
so, I think for tags it looks ok, and its not a proper wordcloud, because I did not want to bother with adding a whole js thing, so its pure html and css.

https://244--rladies-dev.netlify.app/tags/
image


but for categories it looks absolutely crazy, because the rladies category just has so many uses....
https://244--rladies-dev.netlify.app/categories/
image

**Comment by drmowinckels** [comment]
but we need to have a look through tags and categories and clean the posts up a little. We've not had a super clear and enforced policy on tags/category usage, so we should do that maybe even before this PR #243 ?

**Comment by drmowinckels** [comment]
ok. I went away from the wordcloud, to not overcomplicate things. I rather opted for a simple flexbox with terms and counters next to them

image

**Comment by cosimameyer** [comment]
Sorry for taking so long here, the last weeks were a bit crazy. I'm okay with merging - I believe @SoyAndrea's review is missing 🙌

**Pull request merged**
