### PR TITLE
community slack form

### PR DESCRIPTION
**Pull request by SoyAndrea**

### CODE REVIEW

**Comment by drmowinckels** [comment]
@rladies/community-slack

@SoyAndrea  has set up a pretty redirect link to the new community-slack form. It would (on merge) be rladies.org/community-slack-form

If you want to start using that, we'll need to coordinate changing the links on the website and in the guide on how to join the slack.

**Comment by rivaquiroga** [comment]
Looks great! I can update the R-Ladies Guide. 
I added myself as a reviewer so we can merge this PR.

**Review by rivaquiroga — APPROVED** [review]

**Comment by rivaquiroga** [comment]
The updated version of the R-Ladies Guide is in https://github.com/rladies/rladiesguide/pull/115. Once we merge this one, we can merge that one ✨

**Comment by shannonpileggi** [comment]
hi all! just following up on this. how/where is this supposed to appear on the website? we see the links on the about us page but not sure if this is supposed to show somewhere else too.

image

**Comment by drmowinckels** [comment]
we also want to point to this url from the guide, right? 

A positive to having it this way, is that if we consistently use the url we create on our website 

rladies.org/community-slack-form

it means in the future, when we want to change the form or whatever, all we need is to alter the redirect url in this repo, and all other places will point to it correctly. 

So we will need to start sleuthing where else we might point to this form.

**Pull request merged**
