### PR TITLE
Create ghana-kumasi.json

### PR DESCRIPTION
**Pull request by MounaBelaid**

### CODE REVIEW

**Comment by cosimameyer** [comment]
@drmowinckels quick question here about the first failing test. I looked into the issues and it looks like there was [something similar a few years ago](https://github.com/actions/runner-images/issues/282) and I wonder how we handle it. I’m also happy to serve the site locally to verify that it looks good (as a workaround)

**Comment by drmowinckels** [comment]
This type of failure, already in the setup fase, or in any of the steps that use actions from the marketsplace, are usually things that just occur from time to time. Bugs. Best way to handle is usually to wait a little (some hours, maybe even a day) and then retry running the failed jobs in the actions pane. It usually resolves itself.

**Comment by cosimameyer** [comment]
Fantastic, thanks so much! That was also my hope. Retriggering the job works now but when checking the preview I didn’t see the chapter coming up. I believe it’s because it’s prospective (I couldn’t find anything in the wiki about it and will verify my assumption once I’m back at the computer)

**Review by cosimameyer — APPROVED** [review]
Confirmed - it looks good to me ✅

**Pull request merged**
