### PR TITLE
fix #175 & make consistent chapter naming 

### LINKED ISSUE #175: breaking change in renv
There is a breaking change in renv, and its making the website not build :( 
I'm having issues with my mac's developer tools, so I cant get this fixed before I get that sorted.

If @cosimameyer or @SoyAndrea feel adventurous, I think the main job is really to update renv and all packages to the latest and hope that fixes it all. 
Here's some information on renv and continuous integration (which GitHub actions are)
https://rstudio.github.io/renv/articles/ci.html

I can pick this up on Friday, probably, if I manage to fix my computer

### PR DESCRIPTION
**Pull request by drmowinckels**

### CODE REVIEW

**Comment by SoyAndrea** [comment]
Hi @drmowinckels! I have a little question, this PR can be seen from the repo cloned in Rstudio or only here in this link?

**Comment by drmowinckels** [comment]
Yes that is possible, but its a _little_ work. I'd recommend having a read through [Happy git with R](https://happygitwithr.com/index.html). which is an EXCELLENT resource for using GIt inside RStudio :) 

Its quite a lot of information, but if you read the first chapters, so you get some of the basic workflows this book recommends. The section about working locally with a PR inside RStudio is in this section:
https://happygitwithr.com/pr-extend.html

I'm doing quite a lot in this PR, which is a little messy, as I'm just trying to get all the workflows to work again after breaking.

**Comment by drmowinckels** [comment]
This ended up needing more work than expected. I'm going to close it and make anoter PR once I've cleaned up some stuff

**Comment by SoyAndrea** [comment]
Ohhh thank you @drmowinckels, I asked you because I wanted to understand the most effective way to review. If you want I can review another PR 😅

**Pull request closed without merging**
