### PR TITLE
fix #250

### LINKED ISSUE #250: R-Ladies Gaborone appears twice on the R-Ladies Global Chapter page.
Hi ,
I noticed on the R-Ladies Global chapter page, R-Ladies Gaborone appears twice. I think it happened when I updated the PR.
Is it possible to remove the one without the updated PR?
Thank you 🤗
Also, if we need to update anything, can we still use the directory form on the R-Ladies Global website?
I updated my info, and I haven't seen a change yet 🥲

### PR DESCRIPTION
**Pull request by drmowinckels**

### CODE REVIEW

**Comment by cosimameyer** [comment]
Another idea as to why there are two R-Ladies Gabarone chapters showing up: could it be the way the preview is built? (that it basically shows the "old" and the "new" entry?)

**Comment by cosimameyer** [comment]
Making my way through the open tickets - I now also saw Simi's issue (linking it here for reference: https://github.com/rladies/rladies.github.io/issues/250)

**Comment by drmowinckels** [comment]
> Another idea as to why there are two R-Ladies Gabarone chapters showing up: could it be the way the preview is built? (that it basically shows the "old" and the "new" entry?)

no, they start with a clean slate building the whole thing from scratch every time. so that should not be it. I'll look again.

**Comment by drmowinckels** [comment]
@maelle , can I request another set of eyes on this. What are we missing?

**Comment by maelle** [comment]
The chapter appears twice in `chapters_meetup.json`

https://github.com/rladies/rladies.github.io/blob/0d0f1f82c8cb4ed754116ccb856c2deca94ab43c/data/chapters_meetup.json#L644

https://github.com/rladies/rladies.github.io/blob/0d0f1f82c8cb4ed754116ccb856c2deca94ab43c/data/chapters_meetup.json#L614

**Comment by drmowinckels** [comment]
> The chapter appears twice in `chapters_meetup.json`
> 
> https://github.com/rladies/rladies.github.io/blob/0d0f1f82c8cb4ed754116ccb856c2deca94ab43c/data/chapters_meetup.json#L644
> 
> https://github.com/rladies/rladies.github.io/blob/0d0f1f82c8cb4ed754116ccb856c2deca94ab43c/data/chapters_meetup.json#L614

Thank you! That was driving me nuts, and I had made myself blind looking in a specific spot.

**Comment by drmowinckels** [comment]
this is a temp fix really, this file is script generated, so I'm looking into why its duplicated there to begin with.

**Review by SoyAndrea — APPROVED** [review]

**Pull request merged**
